### ISSUE TITLE
Decrease Rendered HTML Size

### ISSUE THREAD

**Issue by VxJasonxV** [bryanveloso/avalonstar-live#7]
When loading the chat interface, it takes seconds to generate a very modest 20 lines of chat. Looking at the rendered source, it turns out that the total HTML being delivered to the client is approximately **4.4MB** (nearly 100,000 lines of CSS!) in it's smallest form. 99% of this space is being used to generate custom CSS classes for all currently known* emoticons:

https://github.com/bryanveloso/avalonstar-live/blob/master/app/controllers/chat.coffee#L16-L26

(* Where currently known means emote sets announced to atvbot and retrieved/stored when a user joins the channel. )

The inefficiency stems from the need to load every single stored emote into static CSS:

https://github.com/bryanveloso/avalonstar-live/blob/master/app/initializers/emoticons.coffee#L33-L37

This process takes time on even beefy systems, and there is a ton of CPU cycles and literally megabytes of transfer being eaten up by generating these unique styles. I imagine that this is also the cause of poor performance of adding new text nodes, such as when a certain high traffic streamer raided you after joining Main Menu :wink:.

**Comment by VxJasonxV** [comment]
DERP EVERY EMOTICON CLASS HAS A UNIQUE BACKGROUND-IMAGE PROPERTY (－‸ლ)
DERP I DIDN'T ACTUALLY READ THE CSS, EMOTES HAVE STATIC SIZE PROPERTIES (－‸ლ)
Come on Jason, please try actually reading the source contents before freaking out about the page size and jumping to conclusions щ(ﾟД ﾟщ)

Editing the first post to point out the inefficiencies and remove any resolution, because I don't currently have a meaningful suggestion.

**Comment by bryanveloso** [comment]
There are two things that'll fix this: 

1. The next release of https://github.com/firebase/emberfire. 
2. IRC v3 support for node-irc, (see https://github.com/martynsmith/node-irc/issues/298).

Believe me, I've been waiting for these things to happen for a long time now.

**Comment by bryanveloso** [comment]
This was fixed by #9.
